-- 코드를 입력하세요
SELECT MONTH(START_DATE) MONTH, crcrh.CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY crcrh
WHERE crcrh.CAR_ID in (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
        GROUP BY CAR_ID
        HAVING COUNT(*) >= 5)
    AND crcrh.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY 1, 2
HAVING RECORDS > 0
ORDER BY 1, 2 DESC;