-- 코드를 입력하세요
SELECT b.CATEGORY, SUM(s.SALES) TOTAL_SALES FROM BOOK b join BOOK_SALES s on b.BOOK_ID = s.BOOK_ID
WHERE s.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY;